In [1]:
#This notebook uses an API that was built utilizing the ESPN Fantasy Football API 
#The documentation can be found here:
#https://github.com/cwendt94/ff-espn-api

%matplotlib inline
#The necessary packages
import pandas as pd
import numpy as np
import seaborn as sns
from ff_espn_api import League
#Info:
league_id=4570371
season=2019

#This is the personal league information
league=League(league_id,2019)
myTeam=league.teams[7]

In [ ]:
#Dictionary of all of the stat fields
statnflgame.statmap.idmap

In [2]:
#Scoring rules (currently incomplete, finish later)
#Some of these won't match with the info in the CSVs but I don't care enough to match everything up this year :P
score_dict={'passing_yds':0.04,'passing_tds':4,'passing_int':-2,'passing_twoptm':2,
            'rushing_yds':0.1,'rushing_tds':6,'rushing_twoptm':2,
           'receiving_yds':0.1,'receiving_rec':1,'receiving_tds':6,'receiving_twopt':2,
           'PAT':1,'kicking_fgmissed':1,'FG0':3,'FG40':4,'FG50':5,
           'kickret_tds':6,'puntret_tds':6,'defense_Int_tds':6,'fumbles_rec_tds':6,
            'BLKKRTD':6,'2PTRET':2,'1PSF':1,'SACK':1,'BLKK':2,'INT':2,
           'fumbles_rec':2,'defense_safe':2,'PA0':5,'PA1':4,'PA7':3,
           'PA14':1,'PA28':-1,'PA35':-3,'PA46':-5,'YA100':5,'YA199':3,
           'YA299':2,'YA399':-1,'YA449':-3,'YA499':-5,'YA549':-6,'YA550':-7,
           'fumbles_lost':-2}

In [3]:
#Make a function to see the remaining free agents
def list_free_agents(league,pos,score_dict):
    dict_keys=set(score_dict.keys())
    rankings=pd.read_csv('{:}_2018_stats.csv'.format(pos))
    curr_free_agents=league.free_agents(position=pos)
    curr_list=[p.name for p in curr_free_agents]
    p_stats=rankings[rankings['Name'].isin(curr_list)].sort_values(['Ranking'])
    p_stats['pts']=0
    p_cols=set(p_stats.columns)
    common_cols=dict_keys.intersection(p_cols)
    for k in common_cols:
        mult_val=score_dict[k]
        sel_col=p_stats[k].fillna(0)
        p_stats['pts']=p_stats['pts']+sel_col*mult_val
    p_full=p_stats.head(10).dropna(axis=1,how='all')
    return(p_full[['Name','Ranking','Team','pts']],p_full)

In [4]:
#SNAKE DRAFT!!
#ROUND 1: RB Pick 
#Position 8
#Before my picks
print(league.draft)
#Look at available top RBs
p_abbrev,p_full=list_free_agents(league,'RB',score_dict)
p_abbrev.sort_values(['pts'],ascending=False)

[]

                   Name  Ranking Team    pts
2   Christian McCaffrey        2  CAR  387.5
1        Saquon Barkley        1  NYG  385.8
3        Todd Gurley II        3  LAR  370.1
0          Alvin Kamara        4   NO  354.2
6       Ezekiel Elliott        5  DAL  331.1
20          James White        7   NE  276.6
5          James Conner        6  PIT  276.0
12        Melvin Gordon        8  LAC  259.1
4         David Johnson        9  ARI  132.0
35    Darrell Henderson        0  LAR   -0.1

In [5]:
#ROUND 2: RB Pick
#Position 3
#Before my picks
p_abbrev,p_full=list_free_agents(league,'RB',score_dict)
p_abbrev.sort_values(['pts'],ascending=False)

                   Name  Ranking Team    pts
2   Christian McCaffrey        2  CAR  387.5
1        Saquon Barkley        1  NYG  385.8
3        Todd Gurley II        3  LAR  370.1
0          Alvin Kamara        4   NO  354.2
6       Ezekiel Elliott        5  DAL  331.1
20          James White        7   NE  276.6
5          James Conner        6  PIT  276.0
12        Melvin Gordon        8  LAC  259.1
4         David Johnson        9  ARI  132.0
35    Darrell Henderson        0  LAR   -0.1

In [6]:
#ROUND 3: WR Pick
#Position 8
#Before my picks
print(league.draft)
#Look at available top WRs
p_abbrev,p_full=list_free_agents(league,'WR',score_dict)
p_abbrev.sort_values(['pts'],ascending=False)

[]

                   Name  Ranking Team    pts
6           Tyreek Hill        1   KC  338.0
0       DeAndre Hopkins        2  HOU  333.5
2         Davante Adams        3   GB  327.6
4           Julio Jones        4  ATL  325.9
7         Antonio Brown        5  OAK  323.7
1        Michael Thomas        6   NO  317.5
11         Adam Thielen        7  MIN  305.3
3   JuJu Smith-Schuster        8  PIT  296.9
9            Mike Evans        9   TB  294.4
14         Stefon Diggs       10  MIN  266.3

In [ ]:
#ROUND 4: WR Pick
#Position 3
#Before my picks
print(league.draft)
#Look at available top WRs
p_abbrev,p_full=list_free_agents(league,'WR',score_dict)
p_abbrev.sort_values(['pts'],ascending=False)

In [ ]:
#ROUND 5: QB Pick
#Position 3
#Before my picks
print(league.draft)
#Look at available top WRs
p_abbrev,p_full=list_free_agents(league,'QB',score_dict)
p_abbrev.sort_values(['pts'],ascending=False)